# Note: this file's config overrides the Netlify UI admin config

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--force --no-progress"

[context.production]

[context.deploy-preview]
